/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package filesearcher.forms;

/**
 *
 * @author Greg
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblRoot = new javax.swing.JLabel();
        txtRoot = new javax.swing.JTextField();
        btnRoot = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblPath = new javax.swing.JLabel();
        txtPath = new javax.swing.JTextField();
        lblTypes = new javax.swing.JLabel();
        txtTypes = new javax.swing.JTextField();
        sepLine = new javax.swing.JSeparator();
        chkLine = new javax.swing.JCheckBox();
        lblLine = new javax.swing.JLabel();
        txtLine = new javax.swing.JTextField();
        chkExclude = new javax.swing.JCheckBox();
        txtExclude = new javax.swing.JTextField();
        chkHide = new javax.swing.JCheckBox();
        chkCase = new javax.swing.JCheckBox();
        chkRegex = new javax.swing.JCheckBox();
        btnFind = new javax.swing.JButton();
        btnOutput = new javax.swing.JButton();
        barMenu = new javax.swing.JMenuBar();
        menPresets = new javax.swing.JMenu();
        itmLoadParameters = new javax.swing.JMenuItem();
        itmSaveParameters = new javax.swing.JMenuItem();
        menLine = new javax.swing.JMenu();
        itmLoadLine = new javax.swing.JMenuItem();
        itmCopyLine = new javax.swing.JMenuItem();
        itmSaveLine = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("File, Line Searcher");

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("File, Line Searcher");
        lblTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblRoot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRoot.setText("Search Folder");

        txtRoot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnRoot.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRoot.setText("Choose");

        lblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblName.setText("Filename");

        txtName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblPath.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPath.setText("Path");

        txtPath.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblTypes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTypes.setText("Filetypes");

        txtTypes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        chkLine.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkLine.setText("Find lines within files");

        lblLine.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLine.setText("Line contains:");

        txtLine.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLine.setEnabled(false);

        chkExclude.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkExclude.setText("Exclude:");
        chkExclude.setEnabled(false);

        txtExclude.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtExclude.setEnabled(false);

        chkHide.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkHide.setText("Hide lines");
        chkHide.setEnabled(false);
        chkHide.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        chkCase.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkCase.setText("Check case");
        chkCase.setEnabled(false);

        chkRegex.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkRegex.setText("Regular expression");
        chkRegex.setEnabled(false);
        chkRegex.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        btnFind.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFind.setText("Find Files");

        btnOutput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnOutput.setText("Open output file");

        menPresets.setText("Presets");

        itmLoadParameters.setText("Load parameters");
        menPresets.add(itmLoadParameters);

        itmSaveParameters.setText("Save parameters");
        menPresets.add(itmSaveParameters);

        barMenu.add(menPresets);

        menLine.setText("Line");

        itmLoadLine.setText("Load saved line");
        menLine.add(itmLoadLine);

        itmCopyLine.setText("Copy saved line");
        menLine.add(itmCopyLine);

        itmSaveLine.setText("Save current line");
        menLine.add(itmSaveLine);

        barMenu.add(menLine);

        setJMenuBar(barMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(chkLine)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkHide))
                    .addComponent(sepLine, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblPath)
                            .addComponent(lblTypes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtName)
                            .addComponent(txtTypes)
                            .addComponent(txtPath)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLine)
                            .addComponent(chkExclude))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtExclude)
                            .addComponent(txtLine)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkCase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkRegex))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOutput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFind))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRoot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(txtRoot))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRoot)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRoot)
                    .addComponent(btnRoot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTypes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sepLine, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkLine)
                    .addComponent(chkHide))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkExclude)
                    .addComponent(txtExclude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCase)
                    .addComponent(chkRegex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOutput)
                    .addComponent(btnFind))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMenu;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnOutput;
    private javax.swing.JButton btnRoot;
    private javax.swing.JCheckBox chkCase;
    private javax.swing.JCheckBox chkExclude;
    private javax.swing.JCheckBox chkHide;
    private javax.swing.JCheckBox chkLine;
    private javax.swing.JCheckBox chkRegex;
    private javax.swing.JMenuItem itmCopyLine;
    private javax.swing.JMenuItem itmLoadLine;
    private javax.swing.JMenuItem itmLoadParameters;
    private javax.swing.JMenuItem itmSaveLine;
    private javax.swing.JMenuItem itmSaveParameters;
    private javax.swing.JLabel lblLine;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPath;
    private javax.swing.JLabel lblRoot;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTypes;
    private javax.swing.JMenu menLine;
    private javax.swing.JMenu menPresets;
    private javax.swing.JSeparator sepLine;
    private javax.swing.JTextField txtExclude;
    private javax.swing.JTextField txtLine;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPath;
    private javax.swing.JTextField txtRoot;
    private javax.swing.JTextField txtTypes;
    // End of variables declaration//GEN-END:variables
}
